# Generated by Django 4.1.4 on 2022-12-26 09:41

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, max-100",
                        max_length=60,
                        unique=True,
                        verbose_name="category_name",
                    ),
                ),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, upload_to=api.models.category_image_path
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=60)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        max_length=60, null=True, verbose_name="product_type"
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                ("categories", models.ManyToManyField(blank=True, to="api.category")),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("size", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubProduct",
            fields=[
                ("name", models.CharField(max_length=60)),
                ("SKU", models.AutoField(primary_key=True, serialize=False)),
                (
                    "store_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("in_stock", models.BooleanField(default=False)),
                ("weight", models.IntegerField(default=1, null=True)),
                ("type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.size"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightUnit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("abbreviation", models.CharField(max_length=10)),
                ("default", models.IntegerField(default=0)),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subproduct"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("units", models.CharField(max_length=60)),
                ("units_sold", models.CharField(max_length=60)),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subproduct"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=60, null=True, verbose_name="type_name"
                    ),
                ),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True, max_length=60, null=True)),
                ("alt_text", models.TextField(max_length=60, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to=api.models.product_image_path
                    ),
                ),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subproduct"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Colour",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("colour", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subproduct"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(max_length=150, null=True, unique=True)),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.subproduct"
                    ),
                ),
            ],
        ),
    ]
