# Generated by Django 4.1.4 on 2022-12-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subproduct",
            name="name",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
