# Generated by Django 4.1.4 on 2022-12-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_subproduct_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subproduct",
            name="name",
            field=models.CharField(default="product_name", max_length=60),
        ),
    ]
